"""Read-only public release audit. Automated flags are candidates, not human review.
Run: python scripts/audit-vocabulary-content.py. No accounts or remote writes.
"""
import json
import re
from collections import Counter
from pathlib import Path

def read(path):
    return json.loads(Path(path).read_text(encoding='utf-8'))

catalog = read('public/vocabulary-catalog.json')
index = read('public/dictionary/index.json')
manifest = read('src/domain/vocabulary/contextSenseOverlay.json')
tasks = read('src/domain/vocabulary/taskSenseBindings.json')
marked = re.compile(r'archaic|obsolete|rare|historical|vulgar|slang|dated|dialect|offensive', re.I)
fragment = re.compile(r'(?:specifically|especially|in particular|including|such as|as|parts|following)\s*:?$|:$', re.I)
members = {}
for m in catalog['memberships']:
    members.setdefault(m['entryId'], []).append(m)
key = lambda r: (r['bookId'], r['unitId'], r['entryId'])
resolved = {key(r) for r in manifest['bindings'] if r['status'] == 'reviewed'}
manual = {key(r): r for r in manifest['bindings'] + manifest['unresolved']}
rows = []
dictionary_count = 0
for e in catalog['entries']:
    filename = index.get(e['term'].lower())
    senses = read(Path('public/dictionary') / filename)['senses'] if filename else []
    dictionary_count += len(senses)
    primary = e['senses'][0] if e['senses'] else {}
    flags = []
    if len(senses) > 1: flags.append('polysemy')
    if len({m['unitId'] for m in members.get(e['id'], [])}) > 1: flags.append('multiple-groups')
    if not primary.get('definition'): flags.append('missing-definition')
    if not primary.get('example'): flags.append('missing-example')
    if marked.search(primary.get('usage', '') + ' ' + primary.get('register', '')): flags.append('marked-primary')
    if fragment.search(primary.get('definition', '')): flags.append('incomplete-definition-candidate')
    if e['term'].lower() in tasks['reviewedCorrections']: flags.append('reviewed-task-sense-mismatch')
    rows.append({'entryId': e['id'], 'term': e['term'], 'flags': flags, 'dictionarySenses': len(senses), 'allSenseIds': [s['id'] for s in senses], 'markedSenseCount': sum(bool(marked.search(s.get('usage', '') + ' ' + s.get('register', ''))) for s in senses)})
by_entry = {r['entryId']: r for r in rows}
membership_rows = []
for m in catalog['memberships']:
    e = by_entry[m['entryId']]; decision = manual.get(key(m))
    membership_rows.append({'bookId': m['bookId'], 'unitId': m['unitId'], 'entryId': m['entryId'], 'term': e['term'], 'flags': e['flags'], 'editorialAudit': bool(decision), 'contextResolved': key(m) in resolved, 'contentReviewed': bool(decision and decision.get('sense')), 'remainingRisk': bool(e['flags'] and key(m) not in resolved), 'reason': decision['reason'] if decision else 'Automated candidate only; editorial contextual review outstanding.'})
by_book = []
for b in catalog['books']:
    ms = [m for m in membership_rows if m['bookId'] == b['id']]
    by_book.append({'bookId': b['id'], 'title': b['title'], 'membershipsScanned': len(ms), 'editoriallyAuditedMemberships': sum(m['editorialAudit'] for m in ms), 'contentCorrectedMemberships': sum(m['contentReviewed'] for m in ms), 'contextResolvedMemberships': sum(m['contextResolved'] for m in ms), 'unresolvedRiskMemberships': sum(m['remainingRisk'] for m in ms)})
summary = {'version': manifest['version'], 'entriesScanned': len(rows), 'membershipsScanned': len(membership_rows), 'groupsScanned': sum(u['kind'] == 'group' for u in catalog['units']), 'dictionarySensesScanned': dictionary_count, 'automatedRiskEntries': sum(bool(r['flags']) for r in rows), 'riskFlags': dict(Counter(f for r in rows for f in r['flags'])), 'editoriallyAuditedMemberships': len(manual), 'contentCorrectedMemberships': len(manifest['bindings']), 'contextResolvedMemberships': len(resolved), 'contextUnresolvedAuditedMemberships': len(manual) - len(resolved), 'unresolvedRiskMemberships': sum(m['remainingRisk'] for m in membership_rows), 'commonModernDefaultsReviewed': len(manifest['defaults']), 'preexistingEditorialTaskSenseBindings': len(tasks['senseIds']), 'taskSenseMismatchesSuppressed': len(tasks['reviewedCorrections']), 'byBook': by_book}
Path('docs/vocabulary-context-audit.json').write_text(json.dumps({'summary': summary, 'entries': rows, 'memberships': membership_rows}, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
lines = ['# Vocabulary context audit', '', 'Generated by `python scripts/audit-vocabulary-content.py` from public release and dictionary files. No user data is read.', '', f"Scanned **{len(rows):,} words, {len(membership_rows):,} memberships, {summary['groupsScanned']} groups and {dictionary_count:,} dictionary senses**.", '', f"Risk-driven editorial review covered **{len(manual)} memberships** across all six books. **{len(manifest['bindings'])}** received reviewed complete definitions, examples and collocations; **{len(resolved)}** have a confirmed thematic context; **{len(manual)-len(resolved)}** still lack evidence of the intended group sense.", '', 'Generic chapters and test parts do not identify a sense without the original sentence. Their common modern content is improved, but context remains unresolved. Fruit-core noun and animal-mating courtship are genuinely absent from the extracted dictionary and use stable editorial IDs. All extracted courtship senses are obsolete courtly-behaviour senses; the animal meaning is not substituted onto one of those IDs. Geography core reuses its broad existing noun ID. Other corrections reuse dictionary IDs. Original dictionary credits and separately attributed editorial text are preserved. Unconfirmed inherited synonyms and word families are cleared from supplements.', '', f"Bound {len(tasks['senseIds'])} preexisting editorial tasks to explicit sense IDs, suppressing {len(tasks['reviewedCorrections'])} mismatched old primary sense tasks. Task correction is separate from membership review. Additionally, {len(manifest['defaults'])} reviewed defaults (fruit, vegetable, the 21 task mismatch words and additional fragment/archaic-priority corrections) improve unbound and standalone content; unknown group intent remains unreviewed.", '', f"Automated candidates: **{summary['automatedRiskEntries']:,} words** and **{summary['unresolvedRiskMemberships']:,} remaining risk memberships**. Polysemy and missing examples are signals, not proof of error. All candidates and unresolved memberships are enumerated in [vocabulary-context-audit.json](vocabulary-context-audit.json). This is not exhaustive human review.", '', '| Book | Memberships scanned | Editorially audited | Content corrected | Context resolved | Remaining risk |', '|---|---:|---:|---:|---:|---:|']
for b in by_book:
    lines.append(f"| {b['title']} | {b['membershipsScanned']} | {b['editoriallyAuditedMemberships']} | {b['contentCorrectedMemberships']} | {b['contextResolvedMemberships']} | {b['unresolvedRiskMemberships']} |")
lines += ['', 'Poetic/dated heaven retains its register while completing the definition; informal gizmo remains intact. No dated word is removed merely for being dated.', '', '## Editorial decisions', '', '| Word | Book / group | Context status | Meaning or unresolved reason |', '|---|---|---|---|']
for r in manifest['bindings'] + manifest['unresolved']:
    lines.append(f"| {r['term']} | {r['bookId']} / {r['unitId']} | {r['status']} | {r.get('sense', {}).get('definition') or r['reason']} |")
Path('docs/vocabulary-context-audit.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(json.dumps(summary, indent=2))

with Path('docs/vocabulary-context-audit.md').open('a', encoding='utf-8') as report:
    report.write('\n## Reviewed default senses\n\n| Word | Stable sense ID | Definition |\n|---|---|---|\n')
    for row in manifest['defaults']:
        report.write(f"| {row['term']} | {row['sense']['id']} | {row['sense']['definition']} |\n")
