"""Read-only complete release corpus/dictionary audit; no production/database writes.
Run: python scripts/audit-vocabulary-content.py
The runtime task-integrity/per-book report is generated by content.test.ts.
"""
import json, re
from pathlib import Path
catalog = json.loads(Path('public/vocabulary-catalog.json').read_text(encoding='utf-8'))
index = json.loads(Path('public/dictionary/index.json').read_text(encoding='utf-8'))
marked = re.compile(r'archaic|obsolete|rare|historical|vulgar|slang|dated|dialect|offensive', re.I)
rows = []
for entry in catalog['entries']:
    filename = index.get(entry['term'].lower())
    senses = json.loads((Path('public/dictionary') / filename).read_text(encoding='utf-8'))['senses'] if filename else []
    primary = entry['senses'][0] if entry['senses'] else {}
    rows.append({'entryId': entry['id'], 'term': entry['term'], 'dictionarySenses': len(senses),
        'markedPrimary': bool(marked.search(primary.get('usage','') + ' ' + primary.get('register',''))),
        'hasDefinition': bool(primary.get('definition')), 'hasExample': bool(primary.get('example')),
        'unmarkedCandidates': [sense['id'] for sense in senses if sense.get('definition') and not marked.search(sense.get('usage','')+' '+sense.get('register',''))]})
output = Path('local/workbench-plan/content-audit.json')
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text(json.dumps({'entries':len(rows),'dictionarySenseCount':sum(row['dictionarySenses'] for row in rows),'entriesAudit':rows},indent=2),encoding='utf-8')
print(f"Audited {len(rows)} entries and {sum(row['dictionarySenses'] for row in rows)} senses; report: {output}")
