// @ts-nocheck
import { ShieldCheck, MessageSquare } from 'lucide-react';
import { ModalFrame } from '../../components/ModalFrame';

export function LegalModal({ view, onClose }: { view: string | null; onClose: () => void }) {
  const privacy = view === 'privacy';
  return <ModalFrame open={Boolean(view)} onClose={onClose} title={privacy ? 'Privacy and terms' : 'Send feedback'}><div className="modal legal-modal">
    <div className="modal-heading"><div><span className="eyebrow">Fieldbook</span><h3>{privacy ? 'Privacy and terms' : 'Send feedback'}</h3></div><span className="modal-icon">{privacy ? <ShieldCheck size={19} /> : <MessageSquare size={19} />}</span></div>
    {privacy ? <><p>Your account uses Supabase for authentication, study records and private recordings. Cloudflare serves the application. Essays, transcripts, scores, vocabulary, plans and recordings are stored on your account; unsynced drafts may also remain in this browser until they are synced or discarded.</p><p>Recordings are not included in JSON backups. External markers receive your work only when you download or copy it and share it yourself. Their privacy terms apply to anything you submit to them.</p><h4>Your data</h4><p>Export your study records from the account menu and download recordings individually. Delete your account from Account. Shared devices should use separate browser profiles; signing out removes this account's draft recovery copy from the browser.</p><h4>Practice and question sources</h4><p>Fieldbook is an independent study tool, not an official IELTS service. Practice scores are feedback, not official exam results or a guarantee of an exam band. Source availability and usage rights should be checked before redistributing question content.</p><h4>Use of the service</h4><p>Keep your account secure and use the service for lawful study. Do not upload content you lack permission to use. Availability and external marking quality may vary. Contact the maintainer through the feedback link for data or service questions.</p></> : <><p>Tell us what blocked your study session or what would make the next one easier. GitHub issues are public; keep essays, recordings and personal information out of your report.</p><a className="btn primary" href="https://github.com/EnosElinsa/ielts-fieldbook/issues/new" target="_blank" rel="noopener noreferrer">Open a feedback issue</a></>}
  </div></ModalFrame>;
}
